export const SET_FILTER_TYPE = 'SET_FILTER_TYPE'
export const SET_SEARCH_TYPE = 'SET SEARCH TYPE'
export const SET_ADD_TYPE = 'SET ADD TYPE'
export const SET_FILTERED_TYPE = 'SET FILTERED TYPE'

export const ADD_TODO_TYPE = 'ADD TODO TYPE'
export const DELETE_TODO_TYPE = 'DELETE TODO TYPE'
export const COMPLETE_TODO_TYPE = 'COMPLETE TODO TYPE'




export const SET_INPUT_TYPE = 'SET INPUT TYPE'


